### ISSUE TITLE
No JS and CSS files under plugin folder

### ISSUE THREAD

**Issue by sravankumard** [BrightcoveLearning/18155-dynamically-change-source-videos#1]
Hi,

I don't see any JS and CSS files under plugin folder, is it removed or not required?

**Comment by mattdraperlynch2** [comment]
I also do not see any of the files mentioned.

**Comment by rcrooks** [comment]
HI @sravankumard and @mattdraperlynch2 if you look at the doc, you'll see that this example can't be turned into a plugin https://support.brightcove.com/brightcove-player-sample-dynamically-change-source-videos

I'll update the readme
